version: '3.7'
services:
  app:
    image: openjdk:17-jdk-slim
    ports:
      - 8000:8000
  redis:
    image: redis
    volumes:
    - ./data:/data
    ports:
    - "6379:6379"
  web:
    image: tomcat
    ports:
    - '8082:8080'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'

